Updated drivermanager to now work as webdriver
updated maven.yml for Chromedriver
Updated pom to add webdriver dependency

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -20,9 +20,16 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
+    - name: Install Chrome and ChromeDriver
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y chromium-browser chromium-chromedriver
+        which chromium-browser
+        which chromedriver
+
     - name: Build with Maven
       run: mvn -B clean test verify || true
-      # `|| true` ensures the workflow continues even if tests or reporting fails
+      # `|| true` ensures workflow continues even if tests fail
 
     - name: Upload Cucumber JSON
       if: always()
